# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  name "cli"
  desc "Official CLI for synthient"
  homepage "https://github.com/synthient/cli"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synthient"
  bash_completion "completions/synthient.bash"
  zsh_completion "completions/synthient.zsh"
  fish_completion "completions/synthient.fish"

  on_macos do
    on_intel do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "b99db33ad2f874852e7d0b94548c073dcb8c2b28c7c8decc8b40861bd5c1f9c3"
    end
    on_arm do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "2c38d51cfe918236e6ed9ab93d593a27ca3b908dd9cbc138a727837f921363b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "9709d022fcf6a120563b90dc8fe8c3153aeefc0e82220523b4523e1bb8451f7b"
    end
    on_arm do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "4ccf293d3e79bfdc8fb355a4e59d8c280abd81b56e28027691058f15d7c2a0b1"
    end
  end

  zap delete: [
      "~/.config/synthient",
    ]

end
