# This file was generated by GoReleaser. DO NOT EDIT.
cask "synthient" do
  name "synthient"
  desc "Official CLI for synthient"
  homepage "https://github.com/synthient/cli"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synthient"
  bash_completion "completions/synthient.bash"
  zsh_completion "completions/synthient.zsh"
  fish_completion "completions/synthient.fish"

  on_macos do
    on_intel do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "740b61e0019fee5d122a9588acf6ddf9d4a53ba888cf3ea185181575999a8129"
    end
    on_arm do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "31abed5ba9dcbabe55e4281208d8ee3cef0deaea740a99d963abdb9694faafdd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "132c100f07147340ab26724e836b3e0348c1b368518d04bdc58718517f5b0227"
    end
    on_arm do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "61ed415676c6b24ff7e49e837f4ec4850b1c62989089657aefc7d7e4284272e5"
    end
  end

  zap delete: [
      "~/.config/synthient",
    ]

end
