# This file was generated by GoReleaser. DO NOT EDIT.
cask "synthient" do
  version "1.5.1"

  on_macos do
    on_intel do
      sha256 "8186024ccd7210ffbd45b72b491f9bd0a18031e859a0b8b79d26d856aabc7894"
      url "https://github.com/synthient/cli/releases/download/v#{version}/synthient_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7407511b8ae8087a9e5a9d1b0eb4c41d34a2dda4de1e2fe8a40120755aed3af0"
      url "https://github.com/synthient/cli/releases/download/v#{version}/synthient_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0bbd2b63c2f66ea1a3620177c8fa5d296241d87b35c810a0fb45d528ad23421d"
      url "https://github.com/synthient/cli/releases/download/v#{version}/synthient_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e769591f01d722fccf96a377ef8ff6532f37b78cec622853a1db2574062c3cc"
      url "https://github.com/synthient/cli/releases/download/v#{version}/synthient_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synthient"
  desc "Official CLI for synthient"
  homepage "https://github.com/synthient/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synthient"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synthient"]
    end
  end

  zap delete: [
      "~/.config/synthient",
    ]

end
