# This file was generated by GoReleaser. DO NOT EDIT.
cask "synthient" do
  name "synthient"
  desc "Official CLI for synthient"
  homepage "https://github.com/synthient/cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synthient"
  bash_completion "completions/synthient.bash"
  zsh_completion "completions/synthient.zsh"
  fish_completion "completions/synthient.fish"

  on_macos do
    on_intel do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "f94d9bb73e4b32ff980fa06bf9ecdf609dfa660339365166186d63e493fbeab4"
    end
    on_arm do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "63d9e64bec9d867f6b9a9dbb40423479c894301ac8ca20e6d12b434c5add2285"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "2af538108181c8ced4b2b7bda8f02b109f243e0646eab2c5db122621b3cd9c4c"
    end
    on_arm do
      url "https://github.com/synthient/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "fcea5c5eb970546fdd01007d718a95e230b2dd6d5ef0cd8cec48bd812a30e072"
    end
  end

  zap delete: [
      "~/.config/synthient",
    ]

end
